# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kyopro Encyclopedia of Algorithms"
email: noshi91d@gmail.com
author: "noshi91"
description:
baseurl: "/algorithm-encyclopedia"  # the subpath of your site, e.g. /blog
url: "https://noshi91.github.io"  # the base hostname & protocol for your site
exclude:
  - "/.bundle"
  - "/.vendor"
  - "/Gemfile"
  - "/Gemfile.lock"
  - "/.git"
  - "/.github"
  - "/.gitignore"
  - "/README.md"
  - "/DESIGN.md"
  - "/CONTRIBUTING.md"
  - "/scripts"

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:year/:month/:day/:title
future: true
timezone: Asia/Tokyo

# Collections settings
collections:
  algorithms:
    permalink: /:title
    sort_by: title
    output: true
  tenkeis:
    permalink: /tenkei/:title
    sort_by: title
    output: true

theme: jekyll-theme-primer

plugins:
  # default on GitHub pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # additional plugins
  - jekyll-octicons
  - jekyll-redirect-from
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true
