name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9.15
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.15

      - name: Install dependencies
        run: pip3 install -r scripts/requirements.txt

      - name: Run scripts/lint.py
        run: python3 scripts/lint.py
